/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_victorcruz;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Victor Jafet Cruz
 */
public class MAIN extends javax.swing.JFrame {

    /**
     * Creates new form MAIN
     */
    public MAIN() {
        initComponents();
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) CB_Titulo.getModel();
        modelo.addElement("Fisico");
        modelo.addElement("Astrofisico");
        modelo.addElement("Ingeniero");
        CB_Titulo.setModel(modelo);
        
        DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) CB_Contextura.getModel();
        modelo1.addElement("Robusto");
        modelo1.addElement("Delgado");
        modelo1.addElement("Sobrepeso");
        CB_Contextura.setModel(modelo1);
        
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) CB_Superficie.getModel();
        modelo2.addElement("Rocoso");
        modelo2.addElement("Gaseoso");
        modelo2.addElement("Liquido");
        CB_Superficie.setModel(modelo2);
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_CrearNave = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Time_desp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombre_nave = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ID_nave = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Cant_maxNave = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comb_res = new javax.swing.JTextField();
        cant_comb = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Time_Land = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Cant_astro = new javax.swing.JTextField();
        JB_CrearNave2 = new javax.swing.JButton();
        CB_Nave = new javax.swing.JComboBox<>();
        JB_ModficarNave = new javax.swing.JButton();
        JB_EliminarNave = new javax.swing.JButton();
        JB_ListarNave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        DistanciaMaxima = new javax.swing.JTextField();
        velocidad = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTA_Nave = new javax.swing.JTextArea();
        JB_LimpiarNave = new javax.swing.JButton();
        JD_CrearAstronauta = new javax.swing.JDialog();
        Nacionalidad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cant_mis = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        JB_CrearAstro2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        peso = new javax.swing.JTextField();
        nombre_astro = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        apellido_astro = new javax.swing.JTextField();
        CB_Contextura = new javax.swing.JComboBox<>();
        CB_Titulo = new javax.swing.JComboBox<>();
        CB_Astronauta = new javax.swing.JComboBox<>();
        JB_ModficarAstro = new javax.swing.JButton();
        JB_EliminarAstro = new javax.swing.JButton();
        JB_ListarAstro = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTA_Astro = new javax.swing.JTextArea();
        JB_LimpiarAstro = new javax.swing.JButton();
        JD_CrearDestino = new javax.swing.JDialog();
        CB_Superficie = new javax.swing.JComboBox<>();
        Sat_OXI = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        dist_dest = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        JB_CrearDestino2 = new javax.swing.JButton();
        nombre_dest = new javax.swing.JTextField();
        JB_ModificarDestino = new javax.swing.JButton();
        JB_EliminaeDestino = new javax.swing.JButton();
        CB_Destino = new javax.swing.JComboBox<>();
        JB_ListarDestino = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTA_ListarDestino = new javax.swing.JTextArea();
        JB_LimpiarDestino = new javax.swing.JButton();
        JD_Simulacion = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        CB_NaveSimulacion = new javax.swing.JComboBox<>();
        CB_DestinoSimulacion = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        JL_Tripulantes = new javax.swing.JList<>();
        CB_AstronautasSimulacion = new javax.swing.JComboBox<>();
        JB_Agregar = new javax.swing.JButton();
        JB_Avanzar = new javax.swing.JButton();
        pg_d = new javax.swing.JProgressBar();
        pg_c = new javax.swing.JProgressBar();
        pg_t = new javax.swing.JProgressBar();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        JB_Detener = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        sp_consumo = new javax.swing.JSpinner();
        sp_v = new javax.swing.JSpinner();
        JB_CrearNave = new javax.swing.JButton();
        JB_CrearAstronauta = new javax.swing.JButton();
        JB_CrearDestino = new javax.swing.JButton();
        JB_Simulacion = new javax.swing.JButton();

        jLabel1.setText("Nombre");

        jLabel2.setText("Cantidad de Astronautas");

        jLabel3.setText("Tiempo Aterrizaje");

        jLabel4.setText("Cantidad Combustible");

        jLabel5.setText("Combustible de Reserva");

        jLabel6.setText("Identificador");

        jLabel8.setText("Cantidad Maxima");

        jLabel9.setText("Tiempo Despegue ");

        JB_CrearNave2.setText("Crear ");
        JB_CrearNave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CrearNave2ActionPerformed(evt);
            }
        });

        JB_ModficarNave.setText("Modficar");
        JB_ModficarNave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ModficarNaveActionPerformed(evt);
            }
        });

        JB_EliminarNave.setText("Eliminar");
        JB_EliminarNave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_EliminarNaveActionPerformed(evt);
            }
        });

        JB_ListarNave.setText("Listar");
        JB_ListarNave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ListarNaveActionPerformed(evt);
            }
        });

        jLabel7.setText("Distancia Maxima");

        jLabel20.setText("Velocidad");

        JTA_Nave.setColumns(20);
        JTA_Nave.setRows(5);
        jScrollPane3.setViewportView(JTA_Nave);

        JB_LimpiarNave.setText("Limpiar");
        JB_LimpiarNave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_LimpiarNaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JD_CrearNaveLayout = new javax.swing.GroupLayout(JD_CrearNave.getContentPane());
        JD_CrearNave.getContentPane().setLayout(JD_CrearNaveLayout);
        JD_CrearNaveLayout.setHorizontalGroup(
            JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearNaveLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DistanciaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JD_CrearNaveLayout.createSequentialGroup()
                        .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(JD_CrearNaveLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(13, 13, 13))
                            .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7)))
                        .addGap(29, 29, 29)
                        .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Time_Land, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(Cant_astro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                        .addComponent(Time_desp, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Cant_maxNave)
                                        .addComponent(ID_nave, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nombre_nave, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(cant_comb, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(comb_res, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_CrearNaveLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JB_ListarNave)
                            .addComponent(CB_Nave, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB_ModficarNave)
                            .addComponent(JB_EliminarNave)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB_LimpiarNave)))
                    .addGroup(JD_CrearNaveLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(JB_CrearNave2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        JD_CrearNaveLayout.setVerticalGroup(
            JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearNaveLayout.createSequentialGroup()
                .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_CrearNaveLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nombre_nave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JD_CrearNaveLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(CB_Nave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_CrearNaveLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ID_nave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JD_CrearNaveLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JB_ModficarNave)))
                .addGap(30, 30, 30)
                .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Cant_maxNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB_EliminarNave))
                .addGap(33, 33, 33)
                .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_ListarNave)
                    .addComponent(jLabel9)
                    .addComponent(Time_desp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_CrearNaveLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Cant_astro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(Time_Land, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(cant_comb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JD_CrearNaveLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_CrearNaveLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comb_res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(JD_CrearNaveLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_LimpiarNave)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(velocidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JB_CrearNave2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JD_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(DistanciaMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jLabel10.setText("Apellido");

        jLabel11.setText("Contextura Fisica");

        jLabel12.setText("Nacionalidad");

        JB_CrearAstro2.setText("Crear ");
        JB_CrearAstro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CrearAstro2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Peso (Kg)");

        jLabel14.setText("Titulo");

        jLabel15.setText("Nombre");

        jLabel16.setText("Cantidad Misiones");

        JB_ModficarAstro.setText("Modificar");
        JB_ModficarAstro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ModficarAstroActionPerformed(evt);
            }
        });

        JB_EliminarAstro.setText("Eliminar");
        JB_EliminarAstro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_EliminarAstroActionPerformed(evt);
            }
        });

        JB_ListarAstro.setText("Listar");
        JB_ListarAstro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ListarAstroActionPerformed(evt);
            }
        });

        JTA_Astro.setColumns(20);
        JTA_Astro.setRows(5);
        jScrollPane2.setViewportView(JTA_Astro);

        JB_LimpiarAstro.setText("Limpiar");
        JB_LimpiarAstro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_LimpiarAstroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JD_CrearAstronautaLayout = new javax.swing.GroupLayout(JD_CrearAstronauta.getContentPane());
        JD_CrearAstronauta.getContentPane().setLayout(JD_CrearAstronautaLayout);
        JD_CrearAstronautaLayout.setHorizontalGroup(
            JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearAstronautaLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JB_CrearAstro2)
                    .addGroup(JD_CrearAstronautaLayout.createSequentialGroup()
                        .addGroup(JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15))
                        .addGap(29, 29, 29)
                        .addGroup(JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(peso, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CB_Contextura, javax.swing.GroupLayout.Alignment.LEADING, 0, 201, Short.MAX_VALUE)
                                .addComponent(cant_mis, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nombre_astro, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(apellido_astro, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Nacionalidad)
                                .addComponent(CB_Titulo, 0, 201, Short.MAX_VALUE)))))
                .addGroup(JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_CrearAstronautaLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JB_EliminarAstro)
                            .addComponent(CB_Astronauta, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB_ModficarAstro)
                            .addComponent(JB_ListarAstro)))
                    .addGroup(JD_CrearAstronautaLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JB_LimpiarAstro)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        JD_CrearAstronautaLayout.setVerticalGroup(
            JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearAstronautaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(nombre_astro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_Astronauta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_CrearAstronautaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(apellido_astro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JD_CrearAstronautaLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(JB_ModficarAstro)))
                .addGroup(JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_CrearAstronautaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(Nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(CB_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(CB_Contextura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(JD_CrearAstronautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cant_mis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addComponent(JB_CrearAstro2))
                    .addGroup(JD_CrearAstronautaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(JB_EliminarAstro)
                        .addGap(39, 39, 39)
                        .addComponent(JB_ListarAstro)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB_LimpiarAstro)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel17.setText("Saturacion Oxigeno");

        jLabel18.setText("Distancia");

        jLabel19.setText("Nombre");

        jLabel22.setText("Tipo Superficie");

        JB_CrearDestino2.setText("Crear ");
        JB_CrearDestino2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CrearDestino2ActionPerformed(evt);
            }
        });

        JB_ModificarDestino.setText("Modificar");
        JB_ModificarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ModificarDestinoActionPerformed(evt);
            }
        });

        JB_EliminaeDestino.setText("Eliminar");
        JB_EliminaeDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_EliminaeDestinoActionPerformed(evt);
            }
        });

        JB_ListarDestino.setText("Listar");
        JB_ListarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ListarDestinoActionPerformed(evt);
            }
        });

        JTA_ListarDestino.setColumns(20);
        JTA_ListarDestino.setRows(5);
        jScrollPane1.setViewportView(JTA_ListarDestino);

        JB_LimpiarDestino.setText("Limpiar");
        JB_LimpiarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_LimpiarDestinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JD_CrearDestinoLayout = new javax.swing.GroupLayout(JD_CrearDestino.getContentPane());
        JD_CrearDestino.getContentPane().setLayout(JD_CrearDestinoLayout);
        JD_CrearDestinoLayout.setHorizontalGroup(
            JD_CrearDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_CrearDestinoLayout.createSequentialGroup()
                .addGroup(JD_CrearDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JD_CrearDestinoLayout.createSequentialGroup()
                        .addGroup(JD_CrearDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JD_CrearDestinoLayout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addGroup(JD_CrearDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addGap(29, 29, 29)
                                .addGroup(JD_CrearDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Sat_OXI, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(JD_CrearDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(JD_CrearDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(nombre_dest, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dist_dest, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CB_Superficie, 0, 201, Short.MAX_VALUE))
                                        .addComponent(JB_CrearDestino2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_CrearDestinoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(JB_LimpiarDestino)
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                    .addGroup(JD_CrearDestinoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JD_CrearDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JB_ModificarDestino)
                            .addComponent(CB_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB_EliminaeDestino)
                            .addComponent(JB_ListarDestino))))
                .addGap(36, 36, 36))
        );
        JD_CrearDestinoLayout.setVerticalGroup(
            JD_CrearDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_CrearDestinoLayout.createSequentialGroup()
                .addGroup(JD_CrearDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_CrearDestinoLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(JD_CrearDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(nombre_dest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(JD_CrearDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(dist_dest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JD_CrearDestinoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(CB_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JB_ModificarDestino)
                        .addGap(18, 18, 18)
                        .addComponent(JB_EliminaeDestino)))
                .addGroup(JD_CrearDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_CrearDestinoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(JD_CrearDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(CB_Superficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JD_CrearDestinoLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(JB_ListarDestino)))
                .addGroup(JD_CrearDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JD_CrearDestinoLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(JD_CrearDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(Sat_OXI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(JB_CrearDestino2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB_LimpiarDestino))
                    .addGroup(JD_CrearDestinoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel21.setText("Nave");

        jLabel23.setText("Direccion");

        jLabel24.setText("Tripulantes");

        JL_Tripulantes.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(JL_Tripulantes);

        JB_Agregar.setText("Agregar");
        JB_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AgregarActionPerformed(evt);
            }
        });

        JB_Avanzar.setText("Avanzar");
        JB_Avanzar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_AvanzarMouseClicked(evt);
            }
        });
        JB_Avanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AvanzarActionPerformed(evt);
            }
        });

        pg_d.setMaximum(1000);
        pg_d.setToolTipText("");
        pg_d.setString(Integer.toString(pg_d.getValue())+" Kilometros");
        pg_d.setStringPainted(true);

        pg_c.setMaximum(50);
        pg_c.setValue(50);
        pg_c.setStringPainted(true);

        pg_t.setMaximum(1440);
        pg_t.setToolTipText("");
        pg_t.setString(Integer.toString(pg_t.getValue())+" Minutos");
        pg_t.setStringPainted(true);

        jLabel29.setText("Combustible de Reserva");

        jLabel30.setText("Tiempo Transcurrido");

        jLabel31.setText("Combustible");

        jButton1.setText("Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JB_Detener.setText("Detener");
        JB_Detener.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JB_DetenerMouseClicked(evt);
            }
        });
        JB_Detener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_DetenerActionPerformed(evt);
            }
        });

        jLabel25.setText("KM/H");

        jLabel26.setText("Velocidad");

        jLabel27.setText("KM/L");

        jLabel28.setText("Consumo");

        javax.swing.GroupLayout JD_SimulacionLayout = new javax.swing.GroupLayout(JD_Simulacion.getContentPane());
        JD_Simulacion.getContentPane().setLayout(JD_SimulacionLayout);
        JD_SimulacionLayout.setHorizontalGroup(
            JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_SimulacionLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_SimulacionLayout.createSequentialGroup()
                        .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JD_SimulacionLayout.createSequentialGroup()
                                .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addGroup(JD_SimulacionLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel31))
                                    .addGroup(JD_SimulacionLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel30))
                                        .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(JD_SimulacionLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(sp_v, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sp_consumo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING)))
                                            .addGroup(JD_SimulacionLayout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(pg_t, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JB_Agregar)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JD_SimulacionLayout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JD_SimulacionLayout.createSequentialGroup()
                                        .addComponent(JB_Avanzar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(80, 80, 80)
                                        .addComponent(JB_Detener, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1))
                                    .addGroup(JD_SimulacionLayout.createSequentialGroup()
                                        .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pg_c, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pg_d, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(75, 75, 75))
                    .addGroup(JD_SimulacionLayout.createSequentialGroup()
                        .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CB_NaveSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CB_DestinoSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(56, 56, 56)
                        .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CB_AstronautasSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        JD_SimulacionLayout.setVerticalGroup(
            JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JD_SimulacionLayout.createSequentialGroup()
                .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JD_SimulacionLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CB_NaveSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB_DestinoSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB_AstronautasSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JD_SimulacionLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sp_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(sp_consumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pg_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pg_c, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JD_SimulacionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                        .addComponent(JB_Agregar)
                        .addGap(14, 14, 14)
                        .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pg_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(55, 55, 55)
                        .addGroup(JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JB_Avanzar)
                            .addComponent(JB_Detener))
                        .addGap(38, 38, 38))
                    .addGroup(JD_SimulacionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(63, 63, 63))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JB_CrearNave.setText("Adminstrar Nave");
        JB_CrearNave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CrearNaveActionPerformed(evt);
            }
        });

        JB_CrearAstronauta.setText("Adminstrar Astronauta");
        JB_CrearAstronauta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CrearAstronautaActionPerformed(evt);
            }
        });

        JB_CrearDestino.setText("Adminstrar Destino");
        JB_CrearDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CrearDestinoActionPerformed(evt);
            }
        });

        JB_Simulacion.setText("Simulacion");
        JB_Simulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SimulacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(JB_CrearNave)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_Simulacion)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JB_CrearAstronauta)
                        .addGap(46, 46, 46)
                        .addComponent(JB_CrearDestino)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_CrearNave)
                    .addComponent(JB_CrearAstronauta)
                    .addComponent(JB_CrearDestino))
                .addGap(64, 64, 64)
                .addComponent(JB_Simulacion)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_CrearNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CrearNaveActionPerformed
       AdminNave admi = new AdminNave("./NaveInfo.vjcm");
       admi.cargarArchivo(); 
       DefaultComboBoxModel model = new DefaultComboBoxModel(admi.getListaNave().toArray());
       CB_Nave.setModel(model);
       Nave();
       
       
        
    }//GEN-LAST:event_JB_CrearNaveActionPerformed

    private void JB_CrearAstronautaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CrearAstronautaActionPerformed
       AdminAstronauta admi = new AdminAstronauta("./AstronautaInfo.vjcm");
       admi.cargarArchivo(); 
       DefaultComboBoxModel model = new DefaultComboBoxModel(admi.getListaAstronautas().toArray());
       CB_Astronauta.setModel(model);
        Astro();
       
       
    }//GEN-LAST:event_JB_CrearAstronautaActionPerformed

    private void JB_CrearDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CrearDestinoActionPerformed
        try {
          AdminDestino admi = new AdminDestino("./DestinoInfo.vjcm");
       admi.cargarArchivo(); 
       DefaultComboBoxModel model = new DefaultComboBoxModel(admi.getListaDestino().toArray());
       CB_Destino.setModel(model);
       Destino();  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR");
        }

    }//GEN-LAST:event_JB_CrearDestinoActionPerformed

    private void JB_CrearNave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CrearNave2ActionPerformed
        try {
            NaveGlobal.setNombre(nombre_nave.getText());
            NaveGlobal.setAstro_abordo(Integer.parseInt(Cant_astro.getText()));
            NaveGlobal.setCant_max(Integer.parseInt(Cant_maxNave.getText()));
            NaveGlobal.setTime(Integer.parseInt(Time_desp.getText()));
            NaveGlobal.setIdent(ID_nave.getText());
            NaveGlobal.setTime_land(Double.parseDouble(Time_Land.getText()));
            NaveGlobal.setCant_comb(Integer.parseInt(cant_comb.getText()));
            NaveGlobal.setCom_res(Integer.parseInt(comb_res.getText()));
            NaveGlobal.setVelocidad(Double.parseDouble(velocidad.getText()));
            NaveGlobal.setDist_max(Double.parseDouble(DistanciaMaxima.getText()));
            
            Nave n = new Nave(NaveGlobal.getNombre(),NaveGlobal.getIdent(),NaveGlobal.getCant_max(),
                    NaveGlobal.getTime(),NaveGlobal.getAstro_abordo(),NaveGlobal.getTime_land(),
                    NaveGlobal.getCant_comb(),NaveGlobal.getCom_res(),NaveGlobal.getVelocidad(),NaveGlobal.getDist_max());
            
            AdminNave AdminNaves=new AdminNave("./NaveInfo.vjcm");
            AdminNaves.cargarArchivo();
            AdminNaves.setNave(n);
            AdminNaves.escribirArchivo();
            
            
            
            
            //Limpia Casillas
            nombre_nave.setText("");
            Cant_astro.setText("");
            ID_nave.setText("");
            Cant_maxNave.setText("");
            Time_Land.setText("");
            Time_desp.setText("");
            comb_res.setText("");
            velocidad.setText("");
            DistanciaMaxima.setText("");
            cant_comb.setText("");
                  
        } catch (Exception e) {
        }
    }//GEN-LAST:event_JB_CrearNave2ActionPerformed

    private void JB_CrearAstro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CrearAstro2ActionPerformed
         AstroGlobal.setNombre(nombre_astro.getText());
         AstroGlobal.setApellido(apellido_astro.getText());
         String contextura = (String) CB_Contextura.getSelectedItem();
         AstroGlobal.setContextura(contextura);
         String titulo = (String) CB_Titulo.getSelectedItem();
         AstroGlobal.setTitulo(titulo);
         AstroGlobal.setNacionalidad(Nacionalidad.getText());
         AstroGlobal.setPeso_kg(Integer.parseInt(peso.getText()));
         AstroGlobal.setCant_misiones(Integer.parseInt(cant_mis.getText()));
         
          Astronautas A = new Astronautas(AstroGlobal.getNombre(),AstroGlobal.getApellido(),AstroGlobal.getNacionalidad(),AstroGlobal.getTitulo(),AstroGlobal.getContextura(),AstroGlobal.getPeso_kg(),AstroGlobal.getCant_misiones());
         
           AdminAstronauta AdminAstro=new AdminAstronauta("./AstronautaInfo.vjcm");
            AdminAstro.cargarArchivo();
            AdminAstro.setAstronautas(A);
            AdminAstro.escribirArchivo();
            
           //Limpia Casillas
           nombre_astro.setText("");
           apellido_astro.setText("");
           Nacionalidad.setText("");
           peso.setText("");
           cant_mis.setText("");
           
                                   
    }//GEN-LAST:event_JB_CrearAstro2ActionPerformed

    private void JB_CrearDestino2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CrearDestino2ActionPerformed
       DestinoGlobal.setNom_dest(nombre_dest.getText());
       DestinoGlobal.setDist_gap(Double.parseDouble(dist_dest.getText()));
       DestinoGlobal.setSat_ox(Double.parseDouble(Sat_OXI.getText()));
       String superficie = (String) CB_Superficie.getSelectedItem();
       DestinoGlobal.setSuperficie(superficie);
       
       Destino D = new Destino(DestinoGlobal.getNom_dest(),DestinoGlobal.getSuperficie(),DestinoGlobal.getDist_gap(),DestinoGlobal.getSat_ox());
       
        AdminDestino AdminDest=new AdminDestino("./DestinoInfo.vjcm");
            AdminDest.cargarArchivo();
            AdminDest.setDestino(D);
            AdminDest.escribirArchivo();
            
           //Limpia Casilla
           nombre_dest.setText("");
           dist_dest.setText("");
           Sat_OXI.setText("");
           
           
       
    }//GEN-LAST:event_JB_CrearDestino2ActionPerformed

    private void JB_ModficarNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ModficarNaveActionPerformed
        try {
           AdminNave admi = new AdminNave("./NaveInfo.vjcm");
        admi.cargarArchivo();
        int indice = CB_Nave.getSelectedIndex();
        admi.getListaNave().get(indice).setAstro_abordo(Integer.parseInt(Cant_astro.getText()));
        admi.getListaNave().get(indice).setCant_comb(Double.parseDouble(cant_comb.getText()));
        admi.getListaNave().get(indice).setCant_max(Integer.parseInt(Cant_maxNave.getText()));
        admi.getListaNave().get(indice).setDist_max(Double.parseDouble(DistanciaMaxima.getText()));
        admi.getListaNave().get(indice).setCom_res(Double.parseDouble(comb_res.getText()));
        admi.getListaNave().get(indice).setTime(Integer.parseInt(Time_desp.getText()));
        admi.getListaNave().get(indice).setTime_land(Integer.parseInt(Time_Land.getText()));
        admi.getListaNave().get(indice).setVelocidad(Double.parseDouble(velocidad.getText()));
        admi.getListaNave().get(indice).setNombre(nombre_nave.getText());
        admi.getListaNave().get(indice).setIdent(ID_nave.getText());

        JOptionPane.showMessageDialog(this, "Modificado con Exito");
        admi.escribirArchivo(); 
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "ERROR");
        }
        
    }//GEN-LAST:event_JB_ModficarNaveActionPerformed

    private void JB_ModficarAstroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ModficarAstroActionPerformed
        try {
          AdminAstronauta admi = new AdminAstronauta("./AstronautaInfo.vjcm");
        admi.cargarArchivo();
        int indice = CB_Astronauta.getSelectedIndex();
        admi.getListaAstronautas().get(indice).setCant_misiones(Integer.parseInt(cant_mis.getText()));
        admi.getListaAstronautas().get(indice).setNombre(nombre_astro.getText());
        admi.getListaAstronautas().get(indice).setApellido(apellido_astro.getText());
        admi.getListaAstronautas().get(indice).setNacionalidad(Nacionalidad.getText());
        admi.getListaAstronautas().get(indice).setPeso_kg(Integer.parseInt(peso.getText()));
        String contextura = (String) CB_Contextura.getSelectedItem();
        admi.getListaAstronautas().get(indice).setContextura(contextura);
        String titulo = (String) CB_Titulo.getSelectedItem();
        admi.getListaAstronautas().get(indice).setTitulo(titulo);
        
        

        JOptionPane.showMessageDialog(this, "Modificado con Exito");
        admi.escribirArchivo();  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR");
        }
        
       
        
    }//GEN-LAST:event_JB_ModficarAstroActionPerformed

    private void JB_EliminarAstroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_EliminarAstroActionPerformed
       try {
            AdminAstronauta admi = new AdminAstronauta("./AstronautaInfo.vjcm");

            int indice = CB_Astronauta.getSelectedIndex();
            admi.cargarArchivo();
            DefaultComboBoxModel model = (DefaultComboBoxModel) CB_Astronauta.getModel();
            model.removeElementAt(indice);
            CB_Astronauta.setModel(model);
            admi.getListaAstronautas().remove(indice);
            admi.escribirArchivo();
            JOptionPane.showMessageDialog(this, "Eliminado");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR");
        }
        
    }//GEN-LAST:event_JB_EliminarAstroActionPerformed

    private void JB_ListarAstroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ListarAstroActionPerformed
        try{ AdminAstronauta admi = new AdminAstronauta("./AstronautaInfo.vjcm");
          admi.cargarArchivo();
          String acum = " "; 
          for (int i = 0; i < admi.getListaAstronautas().size(); i++) {
            acum = acum + i + ") "+ admi.getListaAstronautas().get(i) + "\n"; 
        }
       
        JTA_Astro.setText(acum);
         } catch(Exception e){JOptionPane.showMessageDialog(this, "Error");}
    }//GEN-LAST:event_JB_ListarAstroActionPerformed

    private void JB_ListarNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ListarNaveActionPerformed
        try{ AdminNave admi = new AdminNave("./NaveInfo.vjcm");
          admi.cargarArchivo();
          String acum = " "; 
          for (int i = 0; i < admi.getListaNave().size(); i++) {
            acum = acum + i + ") "+ admi.getListaNave().get(i) + "\n"; 
        }
       
        JTA_Nave.setText(acum);
         } catch(Exception e){JOptionPane.showMessageDialog(this, "Error");}
    }//GEN-LAST:event_JB_ListarNaveActionPerformed

    private void JB_EliminarNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_EliminarNaveActionPerformed
      try {
            AdminNave admi = new  AdminNave("./NaveInfo.vjcm");

            int indice = CB_Nave.getSelectedIndex();
            admi.cargarArchivo();
            DefaultComboBoxModel model = (DefaultComboBoxModel) CB_Nave.getModel();
            model.removeElementAt(indice);
            CB_Nave.setModel(model);
            admi.getListaNave().remove(indice);
            admi.escribirArchivo();
            JOptionPane.showMessageDialog(this, "Eliminado");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR");
        }
    }//GEN-LAST:event_JB_EliminarNaveActionPerformed

    private void JB_ModificarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ModificarDestinoActionPerformed
         try {
          AdminDestino admi = new AdminDestino("./DestinoInfo.vjcm");
        admi.cargarArchivo();
        int indice = CB_Destino.getSelectedIndex();
        admi.getListaDestino().get(indice).setDist_gap(Double.parseDouble(dist_dest.getText()));
        admi.getListaDestino().get(indice).setNom_dest(nombre_dest.getText());
        String superficie = (String) CB_Superficie.getSelectedItem();
        admi.getListaDestino().get(indice).setSuperficie(superficie);
        admi.getListaDestino().get(indice).setSat_ox(Double.parseDouble(Sat_OXI.getText()));
        
        

        JOptionPane.showMessageDialog(this, "Modificado con Exito");
        admi.escribirArchivo();  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR");
        }
    }//GEN-LAST:event_JB_ModificarDestinoActionPerformed

    private void JB_EliminaeDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_EliminaeDestinoActionPerformed
       try {
            AdminDestino admi = new AdminDestino("./DestinoInfo.vjcm");

            int indice = CB_Destino.getSelectedIndex();
            admi.cargarArchivo();
            DefaultComboBoxModel model = (DefaultComboBoxModel) CB_Destino.getModel();
            model.removeElementAt(indice);
            CB_Astronauta.setModel(model);
            admi.getListaDestino().remove(indice);
            admi.escribirArchivo();
            JOptionPane.showMessageDialog(this, "Eliminado");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR");
        }
    }//GEN-LAST:event_JB_EliminaeDestinoActionPerformed

    private void JB_ListarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ListarDestinoActionPerformed
         try{ AdminDestino admi = new AdminDestino("./DestinoInfo.vjcm");
          admi.cargarArchivo();
          String acum = " "; 
          for (int i = 0; i < admi.getListaDestino().size(); i++) {
            acum = acum + i + ") "+ admi.getListaDestino().get(i) + "\n"; 
        }
       
        JTA_ListarDestino.setText(acum);
         } catch(Exception e){JOptionPane.showMessageDialog(this, "Error");}
        
    }//GEN-LAST:event_JB_ListarDestinoActionPerformed

    private void JB_LimpiarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_LimpiarDestinoActionPerformed
        JTA_ListarDestino.setText(" ");
    }//GEN-LAST:event_JB_LimpiarDestinoActionPerformed

    private void JB_LimpiarAstroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_LimpiarAstroActionPerformed
        JTA_Astro.setText(" ");
    }//GEN-LAST:event_JB_LimpiarAstroActionPerformed

    private void JB_LimpiarNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_LimpiarNaveActionPerformed
        JTA_Nave.setText(" ");
    }//GEN-LAST:event_JB_LimpiarNaveActionPerformed

    private void JB_SimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SimulacionActionPerformed
       
        
        AdminNave admi2 = new AdminNave("./NaveInfo.vjcm");
       admi2.cargarArchivo(); 
       DefaultComboBoxModel model2 = new DefaultComboBoxModel(admi2.getListaNave().toArray());
       CB_NaveSimulacion.setModel(model2);
       
        
        AdminAstronauta admi = new AdminAstronauta("./AstronautaInfo.vjcm");
       admi.cargarArchivo(); 
       DefaultComboBoxModel model = new DefaultComboBoxModel(admi.getListaAstronautas().toArray());
       CB_AstronautasSimulacion.setModel(model);
       
        AdminDestino admi1 = new AdminDestino("./DestinoInfo.vjcm");
       admi1.cargarArchivo(); 
       DefaultComboBoxModel model1 = new DefaultComboBoxModel(admi1.getListaDestino().toArray());
       CB_DestinoSimulacion.setModel(model1);
       
       
        Simulacion();
    }//GEN-LAST:event_JB_SimulacionActionPerformed

    private void JB_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AgregarActionPerformed
       DefaultComboBoxModel model_combo = (DefaultComboBoxModel) CB_AstronautasSimulacion.getModel();
        DefaultListModel model_lista = (DefaultListModel) JL_Tripulantes.getModel();
        Astronautas astro = (Astronautas) CB_AstronautasSimulacion.getSelectedItem();
        model_lista.addElement(astro);
        JL_Tripulantes.setModel(model_lista);
    }//GEN-LAST:event_JB_AgregarActionPerformed

    private void JB_AvanzarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AvanzarMouseClicked
        
        try { //por si ya esta iniciado
        Nave nave = (Nave) CB_NaveSimulacion.getSelectedItem(); 
        HT = new administrarTiempo(this.pg_t);
        HD = new administrarDistancia(pg_t, pg_d, sp_v);
        HC = new administrarCombustible(pg_c, pg_d, sp_consumo);
           
                HT.start();
                HD.start();
                HC.start();
                
            
        } catch (Exception e) {

        }
        HT.setAvanzar(true);
        HD.setAvanzar(true);
        HC.setAvanzar(true);
       
    }//GEN-LAST:event_JB_AvanzarMouseClicked

    private void JB_AvanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AvanzarActionPerformed
       
    }//GEN-LAST:event_JB_AvanzarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Reporte();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JB_DetenerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_DetenerMouseClicked
        
        HT.setAvanzar(false);
        HD.setAvanzar(false);
        HC.setAvanzar(false);
       
    }//GEN-LAST:event_JB_DetenerMouseClicked

    private void JB_DetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_DetenerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_DetenerActionPerformed
    public void Reporte() {
        File file = new File("./Reporte.txt");
        FileWriter write;
        PrintWriter writeline;
        //String nave = (String) CB_NaveSimulacion.getSelectedItem();
        Nave nave =  (Nave) CB_NaveSimulacion.getSelectedItem();
        Destino dest = (Destino) CB_DestinoSimulacion.getSelectedItem();
        Astronautas astro = (Astronautas)CB_AstronautasSimulacion.getSelectedItem();
        int tiempo = pg_t.getValue(); 
        int combustible = pg_c.getValue(); 
        int reserva = pg_d.getValue(); 
        String acum = " "; 
        ListModel m = JL_Tripulantes.getModel();
        String acum_tripu =" ";
        for (int i = 0; i < m.getSize(); i++) {
            acum_tripu= acum_tripu + m.toString() + "\n"; 
        }
        
        acum = acum + "Nombre de la nave: " + nave.getNombre() + " Destino: " + dest.getNom_dest() + " Tiempo: " + tiempo + " Combustible: " + combustible + " Reserva: " + reserva;
        
        
        
        if (!file.exists()) {
            try {
                file.createNewFile();
                write = new FileWriter(file, true);
                writeline = new PrintWriter(write);
                writeline.println(acum);
               
                write.close();
                writeline.close();
            } catch (Exception e) {
                e.printStackTrace();
            }//fin del try n catch
        }
        
    }//fin del metodo registrar usuario
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN().setVisible(true);
            }
        });
    }

    public void Nave() {
        JD_CrearNave.pack();
        JD_CrearNave.setModal(true);
        JD_CrearNave.setLocationRelativeTo(this);
        JD_CrearNave.setVisible(true);
    }//fin del llamado del JDialog
    
      public void Astro() {
        JD_CrearAstronauta.pack();
        JD_CrearAstronauta.setModal(true);
        JD_CrearAstronauta.setLocationRelativeTo(this);
        JD_CrearAstronauta.setVisible(true);
    }//fin del llamado del JDialog
      
      public void Destino() {
        JD_CrearDestino.pack();
        JD_CrearDestino.setModal(true);
        JD_CrearDestino.setLocationRelativeTo(this);
        JD_CrearDestino.setVisible(true);
        
    }//fin del llamado del JDialog
      
      public void Simulacion() {
        JD_Simulacion.pack();
        JD_Simulacion.setModal(true);
        JD_Simulacion.setLocationRelativeTo(this);
        JD_Simulacion.setVisible(true);
        
    }//fin del llamado del JDialog
      
      
      
      
    
    
    administrarCombustible HC; 
    administrarTiempo HT; 
    administrarDistancia HD; 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_Astronauta;
    private javax.swing.JComboBox<String> CB_AstronautasSimulacion;
    private javax.swing.JComboBox<String> CB_Contextura;
    private javax.swing.JComboBox<String> CB_Destino;
    private javax.swing.JComboBox<String> CB_DestinoSimulacion;
    private javax.swing.JComboBox<String> CB_Nave;
    private javax.swing.JComboBox<String> CB_NaveSimulacion;
    private javax.swing.JComboBox<String> CB_Superficie;
    private javax.swing.JComboBox<String> CB_Titulo;
    private javax.swing.JTextField Cant_astro;
    private javax.swing.JTextField Cant_maxNave;
    private javax.swing.JTextField DistanciaMaxima;
    private javax.swing.JTextField ID_nave;
    private javax.swing.JButton JB_Agregar;
    private javax.swing.JButton JB_Avanzar;
    private javax.swing.JButton JB_CrearAstro2;
    private javax.swing.JButton JB_CrearAstronauta;
    private javax.swing.JButton JB_CrearDestino;
    private javax.swing.JButton JB_CrearDestino2;
    private javax.swing.JButton JB_CrearNave;
    private javax.swing.JButton JB_CrearNave2;
    private javax.swing.JButton JB_Detener;
    private javax.swing.JButton JB_EliminaeDestino;
    private javax.swing.JButton JB_EliminarAstro;
    private javax.swing.JButton JB_EliminarNave;
    private javax.swing.JButton JB_LimpiarAstro;
    private javax.swing.JButton JB_LimpiarDestino;
    private javax.swing.JButton JB_LimpiarNave;
    private javax.swing.JButton JB_ListarAstro;
    private javax.swing.JButton JB_ListarDestino;
    private javax.swing.JButton JB_ListarNave;
    private javax.swing.JButton JB_ModficarAstro;
    private javax.swing.JButton JB_ModficarNave;
    private javax.swing.JButton JB_ModificarDestino;
    private javax.swing.JButton JB_Simulacion;
    private javax.swing.JDialog JD_CrearAstronauta;
    private javax.swing.JDialog JD_CrearDestino;
    private javax.swing.JDialog JD_CrearNave;
    private javax.swing.JDialog JD_Simulacion;
    private javax.swing.JList<String> JL_Tripulantes;
    private javax.swing.JTextArea JTA_Astro;
    private javax.swing.JTextArea JTA_ListarDestino;
    private javax.swing.JTextArea JTA_Nave;
    private javax.swing.JTextField Nacionalidad;
    private javax.swing.JTextField Sat_OXI;
    private javax.swing.JTextField Time_Land;
    private javax.swing.JTextField Time_desp;
    private javax.swing.JTextField apellido_astro;
    private javax.swing.JTextField cant_comb;
    private javax.swing.JTextField cant_mis;
    private javax.swing.JTextField comb_res;
    private javax.swing.JTextField dist_dest;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nombre_astro;
    private javax.swing.JTextField nombre_dest;
    private javax.swing.JTextField nombre_nave;
    private javax.swing.JTextField peso;
    public javax.swing.JProgressBar pg_c;
    public javax.swing.JProgressBar pg_d;
    public javax.swing.JProgressBar pg_t;
    private javax.swing.JSpinner sp_consumo;
    private javax.swing.JSpinner sp_v;
    private javax.swing.JTextField velocidad;
    // End of variables declaration//GEN-END:variables
    Nave NaveGlobal = new Nave();
    Astronautas AstroGlobal = new Astronautas();
    Destino DestinoGlobal = new Destino();
    ArrayList <Nave> listNave = new ArrayList();
    ArrayList <Astronautas> listAstro = new ArrayList();
    ArrayList <Destino> listDest = new ArrayList();
    
    
}
